#!/usr/bin/env node
/**
 * Page → file map generator. Writes docs/PAGE_MAP.md.
 *
 * Purpose: an agent asked to change "the resume page" opens ONE line here and knows exactly
 * which component, CSS, tests and BottomNav spacer belong to it — no repo-wide grep.
 *
 * Sources it parses (no hand-maintained lists):
 *   - src/App.jsx           `case '<tab>':` blocks → first <Component rendered
 *   - src/components/Profile.jsx  `if (activePage === '<page>')` blocks → first <Component rendered
 *   - every component file  → line count, imported .css, sibling *.test.*, trailing spacer heights
 *
 * Usage: node scripts/gen_page_map.mjs [--check]   (--check: exit 1 if the map is stale)
 */
import { readFileSync, writeFileSync, existsSync, readdirSync, statSync, mkdirSync } from 'fs';
import { join, dirname, relative, basename, resolve } from 'path';
import { fileURLToPath } from 'url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');
const OUT = join(ROOT, 'docs', 'PAGE_MAP.md');
const BIG = 800; // files above this many lines are flagged as split candidates

const read = (p) => readFileSync(p, 'utf8');
const lines = (p) => read(p).split('\n').length;
const rel = (p) => relative(ROOT, p);

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (/\.(jsx?|css)$/.test(name)) acc.push(p);
  }
  return acc;
}
const all = walk(SRC);
const code = all.filter((p) => /\.jsx?$/.test(p) && !/\.test\./.test(p));

/** Resolve `import X from './y'` inside `file` to an absolute path (or null). */
function resolveImport(file, name) {
  const m = read(file).match(new RegExp(`import\\s+(?:\\{[^}]*\\b${name}\\b[^}]*\\}|${name})[^'"]*['"]([^'"]+)['"]`));
  if (!m || !m[1].startsWith('.')) return null;
  const base = resolve(dirname(file), m[1]);
  for (const ext of ['', '.jsx', '.js', '/index.jsx', '/index.js']) if (existsSync(base + ext) && statSync(base + ext).isFile()) return base + ext;
  return null;
}

/** For each `marker` match, the first JSX component rendered within the next `span` lines. */
function routes(file, re, span = 25) {
  const src = read(file).split('\n');
  const out = [];
  src.forEach((line, i) => {
    const m = line.match(re);
    if (!m) return;
    for (let j = i; j < Math.min(src.length, i + span); j++) {
      const c = src[j].match(/<([A-Z][A-Za-z0-9]+)[\s/>]/);
      if (c && !['Suspense', 'Fragment', 'AnimatePresence'].includes(c[1])) {
        out.push({ key: m[1], component: c[1], line: i + 1, file: resolveImport(file, c[1]) });
        return;
      }
    }
    out.push({ key: m[1], component: '(inline)', line: i + 1, file: null });
  });
  return out;
}

function facts(file) {
  if (!file) return { lines: '-', css: '-', tests: '-', spacer: '-' };
  const src = read(file);
  const css = [...src.matchAll(/import\s+['"](\.[^'"]+\.css)['"]/g)].map((m) => rel(resolve(dirname(file), m[1])));
  const stem = basename(file).replace(/\.jsx?$/, '');
  const tests = all.filter((p) => basename(p).startsWith(stem + '.test.')).map(rel);
  const spacers = [...new Set([...src.matchAll(/height:\s*'(\d+)px',\s*minHeight/g)].map((m) => +m[1]).filter((n) => n >= 40).map((n) => n + 'px'))];
  return { lines: lines(file), css: css.join('<br>') || '-', tests: tests.join('<br>') || '-', spacer: spacers.join(', ') || '-' };
}

const link = (p, line) => (p ? `[${rel(p)}](../${rel(p)}${line ? `#L${line}` : ''})` : '-');
const row = (r, host) => {
  const f = facts(r.file);
  return `| \`${r.key}\` | ${r.component} | ${link(r.file)} | ${f.lines} | ${f.css} | ${f.tests} | ${f.spacer} | ${link(host, r.line)} |`;
};
const HEAD = '| Key | Component | File | Lines | CSS | Tests | Spacer | Routed at |\n|---|---|---|---:|---|---|---|---|';

const app = join(SRC, 'App.jsx');
const profile = join(SRC, 'components', 'Profile.jsx');
const tabs = routes(app, /case '([a-z_]+)':/);
const pages = routes(profile, /activePage === '([A-Za-z_]+)'\)\s*\{/);

const big = code.filter((p) => !p.includes('/locales/')).map((p) => ({ p, n: lines(p) })).filter((x) => x.n > BIG).sort((a, b) => b.n - a.n);

const md = `# PAGE_MAP — which file owns which screen

> Auto-generated by \`node scripts/gen_page_map.mjs\`. **Do not edit by hand.**
> Agents: find the screen here, open only that file (and only the lines you need). Do not grep the whole repo.
> Mirror \`web-start-michi-app/\` is synced by script — never edit it directly.

## 1. Bottom tabs (\`src/App.jsx\` → \`renderContent\`)
${HEAD}
${tabs.map((r) => row(r, app)).join('\n')}

## 2. Profile sub-pages (\`src/components/Profile.jsx\` → \`activePage\`)
${HEAD}
${pages.map((r) => row(r, profile)).join('\n')}

Profile main screen (no \`activePage\`, or \`'main'\`): ${link(join(SRC, 'components', 'profile', 'ProfileMainView.jsx'))}

## 3. Split candidates (> ${BIG} lines) — edit with extra care, read by line range only
| File | Lines |
|---|---:|
${big.map((x) => `| ${link(x.p)} | ${x.n} |`).join('\n')}

## 4. Shared building blocks (touching these affects many screens)
| Area | Files |
|---|---|
| Layout / scroll contract | \`src/index.css\`, \`src/App.css\` (global — change only on explicit request) |
| Bottom navigation | ${link(join(SRC, 'components', 'BottomNav.jsx'))} |
| i18n (7 locales) | \`src/locales/{ja,uz,en,ru,zh,vi,ne}.js\` — add every key to all 7 |
| API base | ${link(join(SRC, 'config', 'api.js'))} |
`;

if (process.argv.includes('--check')) {
  const cur = existsSync(OUT) ? read(OUT) : '';
  if (cur !== md) { console.error('PAGE_MAP.md is stale. Run: node scripts/gen_page_map.mjs'); process.exit(1); }
  console.log('PAGE_MAP.md up to date');
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, md);
  console.log(`PAGE_MAP.md: ${tabs.length} tabs, ${pages.length} profile pages, ${big.length} split candidates`);
}
