import fs from 'fs';
let content = fs.readFileSync('src/i18n.js', 'utf8');
content = content.replace('turnOnBtn: "Yoqish",', 'turnOnBtn: "Yoqish",\n      turnOffBtn: "O\'chirish",');
content = content.replace('turnOnBtn: "起動する",', 'turnOnBtn: "起動する",\n      turnOffBtn: "停止する",');
content = content.replace('turnOnBtn: "Turn On",', 'turnOnBtn: "Turn On",\n      turnOffBtn: "Turn Off",');
content = content.replace('turnOnBtn: "Bật lên",', 'turnOnBtn: "Bật lên",\n      turnOffBtn: "Tắt",');
content = content.replace('turnOnBtn: "开启",', 'turnOnBtn: "开启",\n      turnOffBtn: "关闭",');
content = content.replace('turnOnBtn: "खोल्नुहोस्",', 'turnOnBtn: "खोल्नुहोस्",\n      turnOffBtn: "बन्द गर्नुहोस्",');
fs.writeFileSync('src/i18n.js', content, 'utf8');
console.log('Injected successfully');
