const resumeTranslations = {
  "uz": {
    "createResume": "Yapon Rezyumesi (履歴書)",
    "downloadPDF": "PDF Yuklab Olish",
    "postalCodeLabel": "Pochta indeksi",
    "furiganaLabel": "Furigana (Ism o'qilishi)",
    "genderLabel": "Jins",
    "male": "Erkak",
    "female": "Ayol",
    "phoneLabel": "Telefon raqam",
    "motivationLabel": "Ishga kirish sababi (志望動機)",
    "selfPRLabel": "O'z-o'zini taqdim etish (自己PR)",
    "hobbiesLabel": "Qiziqishlar va maxsus ko'nikmalar",
    "personalRequestsLabel": "Shaxsiy istaklar (ish shartlari)",
    "resumeBuilderTitle": "Yapon Rezyumesi Generator",
    "stepLabel": "Bosqich",
    "nextBtn": "Keyingi",
    "prevBtn": "Orqaga",
    "previewPDF": "PDFni ko'rib chiqish",
    "loadingFont": "Yapon shrifti yuklanmoqda...",
    "generatingPDF": "PDF tayyorlanmoqda...",
    "downloading": "Yuklab olinmoqda...",
    "completed": "Yuklash yakunlandi",
    "step1Desc": "Rirekisho rezyumesi uchun shaxsiy ma'lumotlaringizni to'g'rilang. Ismlar katakana va yapon formatida yozilishi maqsadga muvofiq.",
    "step2Desc": "Yaponiyadagi manzilingiz va aloqa ma'lumotlari. Pochta indeksini to'g'ri kiritsangiz kompaniyalar sizni tez topishadi.",
    "step3Desc": "O'qigan maktablar, kollejlar va oliy ta'lim muassasalarini qo'shing (Yil va oy formatida).",
    "step4Desc": "Avvalgi ishlagan kompaniyalaringiz, lavozimingiz va boshlanish/tugash sanalari. Haydovchilik tajribalaringizni yoritish muhim.",
    "step5Desc": "Yapon firmalarida eng ko'p e'tibor qaratiladigan bo'lim. \"Nima sababdan ushbu ishga topshiryapsiz?\" va \"O'z kuchli taraflaringiz (Self-PR)\" haqida yozing.",
    "step6Desc": "Barcha ma'lumotlar standart yapon Rirekisho formatidagi PDF shakliga keltirildi. Quyida uni tekshirishingiz yoki yuklab olishingiz mumkin.",
    "step6Title": "Tayyor! PDF Rezyume Yaratildi",
    "contactInfo": "Aloqa va Manzil",
    "remove": "O'chirish",
    "schoolName": "Muassasa nomi (masalan: ○○ universiteti)",
    "degree": "Mutaxassislik/Daraja (masalan: bakalavr)",
    "company": "Kompaniya",
    "companyName": "Kompaniya nomi",
    "position": "Lavozim (masalan: yuk mashinasi haydovchisi)",
    "startDate": "Boshlanish sanasi",
    "endDate": "Tugash sanasi",
    "currentPositionCheckbox": "Hozirgi vaqtda ishlayapman",
    "addWork": "Ish joyi qo'shish",
    "addEducation": "Ta'lim qo'shish",
    "licensesQualifications": "Guvohnoma va Sertifikatlar",
    "otherCertificates": "Maxsus sertifikatlar",
    "finishBtn": "Tugatish",
    "callBtn": "Qo'ng'iroq qilish",
    "fullNameLabel": "Ism va familiya",
    "katakanaNameLabel": "Katakanada yozilishi",
    "fullNameHint": "Yapon tilida to'ldirish uchun lotin harflarida (Masalan: ALIMOV ANVAR) yoki kanjida (Masalan: 山田 太郎) yozing.",
    "furiganaHint": "Ismingizning yaponcha katakana talaffuzi (Masalan: アリモフ アンバル yoki ヤマダ タロウ).",
    "dobHint": "Tug'ilgan kuningizni kun, oy va yaponcha davr (Era) yili ketma-ketligida tanlang.",
    "day": "Kun",
    "month": "Oy",
    "year": "Yil",
    "daySuffix": "kun",
    "monthSuffix": "oy",
    "yearSuffix": "yil",
    "birthPlaceLabel": "Tug'ilgan joyi",
    "birthPlaceHint": "Tug'ilgan mamlakatingiz yoki viloyatingiz (Masalan: O'zbekiston, Samarqand).",
    "birthPlacePlaceholder": "Masalan: O'zbekiston",
    "nationalityLabel": "Millati",
    "nationalityHint": "Fuqaroligingiz yoki millatingiz (Masalan: O'zbekiston).",
    "nationalityPlaceholder": "Masalan: O'zbekistonlik",
    "motivationPR": "Motivatsiya va O'z-o'zini taqdim etish",
    "refreshPreview": "Yangilash",
    "pdfPreviewRendering": "📄 PDF ko'rib chiqish yuklanmoqda...",
    "lic_futsu": "Oddiy yengil (Futsu)",
    "lic_chugata": "O'rta yuk mashinasi (Chugata)",
    "lic_oogata": "Katta yuk mashinasi (Oogata)",
    "lic_tokushu": "Maxsus transport (Tokushu)",
    "cert_forklift": "Forklift (フォークリフト)",
    "cert_crane": "Kran (クレーン)",
    "cert_towing": "Tirkama shatakka olish (牽引)",
    "admissionDateLabel": "Kirgan sanasi",
    "gradDateLabel": "Bitirgan sanasi",
    "openInNewTab": "Yangi oynada ochish"
  },
  "ja": {
    "createResume": "履歴書作成 (PDF)",
    "downloadPDF": "PDFダウンロード",
    "postalCodeLabel": "郵便番号",
    "furiganaLabel": "ふりがな",
    "genderLabel": "性別",
    "male": "男",
    "female": "女",
    "phoneLabel": "電話番号",
    "motivationLabel": "志望動機",
    "selfPRLabel": "自己PR",
    "hobbiesLabel": "趣味・特技",
    "personalRequestsLabel": "本人希望記入欄",
    "resumeBuilderTitle": "履歴書作成ツール",
    "stepLabel": "ステップ",
    "nextBtn": "次へ",
    "prevBtn": "前へ",
    "previewPDF": "プレビュー",
    "loadingFont": "日本語フォントを読み込み中...",
    "generatingPDF": "PDFを作成中...",
    "downloading": "ダウンロード中...",
    "completed": "ダウンロード完了",
    "step1Desc": "履歴書に必要な個人情報を入力してください。お名前のふりがな（カタカナ）や生年月日などを正しく入力してください。",
    "step2Desc": "日本国内での現住所と連絡先を入力してください。郵便番号を正しく入力すると、企業からの連絡やアクセスがスムーズになります。",
    "step3Desc": "学歴（高校、専門学校、大学など）を入力してください。（年・月形式）",
    "step4Desc": "これまでの職歴を入力してください。特に運転経験やドライバーとしての経歴を詳しく記入すると効果的です。",
    "step5Desc": "志望動機、自己PR、趣味・特技などを入力してください。採用担当者が最も注目する項目です。",
    "step6Desc": "入力された情報をもとに、标准的な日本式の履歴書PDFが作成されました。プレビューを確認し、ダウンロードしてください。",
    "step6Title": "履歴書PDFの作成が完了しました！",
    "contactInfo": "連絡先・住所",
    "remove": "削除",
    "schoolName": "学校名（例：○○高等学校）",
    "degree": "学部・学科・専攻（例：卒業）",
    "company": "企業",
    "companyName": "企業名/会社名",
    "position": "職種・業務内容（例：トラック運転手）",
    "startDate": "開始年月",
    "endDate": "終了年月",
    "currentPositionCheckbox": "現在も在職中",
    "addWork": "職歴を追加",
    "addEducation": "学歴を追加",
    "licensesQualifications": "免許・資格",
    "otherCertificates": "特別教育・その他資格",
    "finishBtn": "完了",
    "callBtn": "電話する",
    "fullNameLabel": "氏名（漢字またはローマ字）",
    "katakanaNameLabel": "ふりがな（カタカナ）",
    "fullNameHint": "ローマ字（例: YAMADA TARO）または漢字（例: 山田 太郎）で入力してください。",
    "furiganaHint": "お名前のカタカナ読みを入力してください（例: ヤマダ タロウ）。",
    "dobHint": "生年月日を日、月、和暦（年）の順で選択してください。",
    "day": "日",
    "month": "月",
    "year": "年",
    "daySuffix": "日",
    "monthSuffix": "月",
    "yearSuffix": "年",
    "birthPlaceLabel": "出生地",
    "birthPlaceHint": "出生国または出身地を入力してください（例：日本、東京都）。",
    "birthPlacePlaceholder": "例：日本",
    "nationalityLabel": "国籍",
    "nationalityHint": "国籍を入力してください（例：日本）。",
    "nationalityPlaceholder": "例：日本",
    "motivationPR": "志望動機・自己PR",
    "refreshPreview": "プレビュー更新",
    "pdfPreviewRendering": "📄 PDFプレビューを作成中...",
    "lic_futsu": "普通免許",
    "lic_chugata": "中型免許",
    "lic_oogata": "大型免許",
    "lic_tokushu": "特殊免許",
    "cert_forklift": "フォークリフト",
    "cert_crane": "クレーン",
    "cert_towing": "牽引",
    "admissionDateLabel": "入学年月",
    "gradDateLabel": "卒業年月",
    "openInNewTab": "別タブで表示"
  },
  "en": {
    "createResume": "Japanese Resume (Rirekisho)",
    "downloadPDF": "Download PDF",
    "postalCodeLabel": "Postal Code",
    "furiganaLabel": "Furigana (Name Reading)",
    "genderLabel": "Gender",
    "male": "Male",
    "female": "Female",
    "phoneLabel": "Phone Number",
    "motivationLabel": "Motivation / Reason for applying",
    "selfPRLabel": "Self-Promotion (Self-PR)",
    "hobbiesLabel": "Hobbies & Skills",
    "personalRequestsLabel": "Personal Requests / Conditions",
    "resumeBuilderTitle": "Japanese Resume Builder",
    "stepLabel": "Step",
    "nextBtn": "Next",
    "prevBtn": "Back",
    "previewPDF": "Preview PDF",
    "loadingFont": "Loading Japanese font...",
    "generatingPDF": "Generating PDF...",
    "downloading": "Downloading...",
    "completed": "Completed",
    "step1Desc": "Please fill in your personal information. It is recommended to write names in Latin and Katakana correctly.",
    "step2Desc": "Your address and contact information in Japan. Enter the correct postal code to help companies reach you.",
    "step3Desc": "Add your education history (schools, colleges, universities) in year and month format.",
    "step4Desc": "Enter your work history, positions, and dates. Highlighting driving experience is highly recommended.",
    "step5Desc": "Fill in your motivation, self-promotion (PR), hobbies, and personal requests.",
    "step6Desc": "Your standard Japanese Rirekisho PDF has been generated. You can preview or download it below.",
    "step6Title": "Ready! PDF Resume Generated",
    "contactInfo": "Contact & Address",
    "remove": "Remove",
    "schoolName": "Institution Name (e.g., ○○ University)",
    "degree": "Degree/Major (e.g., Bachelor)",
    "company": "Company",
    "companyName": "Company Name",
    "position": "Position (e.g., Truck Driver)",
    "startDate": "Start Date",
    "endDate": "End Date",
    "currentPositionCheckbox": "Currently working here",
    "addWork": "Add Work History",
    "addEducation": "Add Education",
    "licensesQualifications": "Licenses & Qualifications",
    "otherCertificates": "Special Certificates",
    "finishBtn": "Finish",
    "callBtn": "Call",
    "fullNameLabel": "Full Name",
    "katakanaNameLabel": "Katakana Pronunciation",
    "fullNameHint": "Enter in English letters (e.g., ALIMOV ANVAR) or Kanji (e.g., 山田 太郎).",
    "furiganaHint": "Enter your name pronunciation in Japanese Katakana (e.g., アリモフ アンバル or ヤマダ タロウ).",
    "dobHint": "Select your birth date in sequence: day, month, and Japanese Era year.",
    "day": "Day",
    "month": "Month",
    "year": "Year",
    "daySuffix": "day",
    "monthSuffix": "month",
    "yearSuffix": "year",
    "birthPlaceLabel": "Place of Birth",
    "birthPlaceHint": "Enter your country or place of birth (e.g., United Kingdom, London).",
    "birthPlacePlaceholder": "e.g., United Kingdom",
    "nationalityLabel": "Nationality",
    "nationalityHint": "Enter your nationality (e.g., British).",
    "nationalityPlaceholder": "e.g., British",
    "motivationPR": "Motivation & Self-PR",
    "refreshPreview": "Refresh Preview",
    "pdfPreviewRendering": "📄 PDF preview rendering...",
    "lic_futsu": "Regular Car (Futsu)",
    "lic_chugata": "Medium Truck (Chugata)",
    "lic_oogata": "Large Truck (Oogata)",
    "lic_tokushu": "Special License (Tokushu)",
    "cert_forklift": "Forklift",
    "cert_crane": "Crane",
    "cert_towing": "Towing",
    "admissionDateLabel": "Admission Date",
    "gradDateLabel": "Graduation Date",
    "openInNewTab": "Open in New Tab"
  },
  "ru": {
    "createResume": "Японское резюме (履歴書)",
    "downloadPDF": "Скачать PDF",
    "postalCodeLabel": "Почтовый индекс",
    "furiganaLabel": "Фуригана (чтение имени)",
    "genderLabel": "Пол",
    "male": "Мужской",
    "female": "Женский",
    "phoneLabel": "Номер телефона",
    "motivationLabel": "Мотивация / Причина подачи",
    "selfPRLabel": "Самопрезентация (Self-PR)",
    "hobbiesLabel": "Хобби и особые навыки",
    "personalRequestsLabel": "Личные пожелания (условия)",
    "resumeBuilderTitle": "Конструктор резюме",
    "stepLabel": "Шаг",
    "nextBtn": "Далее",
    "prevBtn": "Назад",
    "previewPDF": "Предпросмотр PDF",
    "loadingFont": "Загрузка японского шрифта...",
    "generatingPDF": "Создание PDF...",
    "downloading": "Скачивание...",
    "completed": "Готово",
    "step1Desc": "Пожалуйста, заполните личную информацию. Рекомендуется правильно указать имя латиницей и катаканой.",
    "step2Desc": "Ваш адрес и контактные данные в Японии. Укажите правильный почтовый индекс, чтобы компаниям было проще связаться с вами.",
    "step3Desc": "Добавьте информацию об образовании (школы, колледжи, университеты) в формате года и месяца.",
    "step4Desc": "Введите опыт работы, должности и даты. Крайне рекомендуется выделить водительский стаж.",
    "step5Desc": "Заполните мотивацию, самопрезентацию (Self-PR), хобби и особые пожелания.",
    "step6Desc": "Ваше резюме в формате Rirekisho успешно создано. Вы можете предварительно просмотреть его или скачать ниже.",
    "step6Title": "Готово! PDF резюме успешно создано",
    "contactInfo": "Контактная информация",
    "remove": "Удалить",
    "schoolName": "Название учебного заведения (например, Университет ○○)",
    "degree": "Специальность/Степень (например, бакалавр)",
    "company": "Компания",
    "companyName": "Название компании",
    "position": "Должность (например, водитель грузовика)",
    "startDate": "Дата начала",
    "endDate": "Дата окончания",
    "currentPositionCheckbox": "Работаю по настоящее время",
    "addWork": "Добавить место работы",
    "addEducation": "Добавить обучение",
    "licensesQualifications": "Лицензии и квалификации",
    "otherCertificates": "Специальные сертификаты",
    "finishBtn": "Завершить",
    "callBtn": "Позвонить",
    "fullNameLabel": "Имя и фамилия",
    "katakanaNameLabel": "Запись катаканой",
    "fullNameHint": "Заполните латиницей (например: ALIMOV ANVAR) или японскими иероглифами (например: 山田 太郎) для соответствия японским стандартам.",
    "furiganaHint": "Произношение имени японской катаканой (например: アリモフ アンバル или ヤマダ Таロウ).",
    "dobHint": "Выберите дату рождения последовательно: день, месяц и год японской эры.",
    "day": "День",
    "month": "Месяц",
    "year": "Год",
    "motivationPR": "Мотивация и самопрезентация",
    "refreshPreview": "Обновить предпросмотр",
    "pdfPreviewRendering": "📄 Создание предпросмотра PDF...",
    "lic_futsu": "Обычные права (Futsu)",
    "lic_chugata": "Средние грузовики (Chugata)",
    "lic_oogata": "Большие грузовики (Oogata)",
    "lic_tokushu": "Спецтехника (Tokushu)",
    "cert_forklift": "Автопогрузчик",
    "cert_crane": "Кран",
    "cert_towing": "Буксировка",
    "admissionDateLabel": "Дата поступления",
    "gradDateLabel": "Дата окончания",
    "openInNewTab": "Открыть в новой вкладке"
  },
  "vi": {
    "createResume": "Tạo sơ yếu lý lịch Nhật",
    "downloadPDF": "Tải xuống PDF",
    "postalCodeLabel": "Mã bưu điện",
    "furiganaLabel": "Furigana (Cách đọc tên)",
    "genderLabel": "Giới tính",
    "male": "Nam",
    "female": "Nữ",
    "phoneLabel": "Số điện thoại",
    "motivationLabel": "Động lực / Lý do ứng tuyển",
    "selfPRLabel": "Giới thiệu bản thân (Self-PR)",
    "hobbiesLabel": "Sở thích & kỹ năng đặc biệt",
    "personalRequestsLabel": "Yêu cầu cá nhân",
    "resumeBuilderTitle": "Trình tạo CV tiếng Nhật",
    "stepLabel": "Bước",
    "nextBtn": "Tiếp theo",
    "prevBtn": "Quay lại",
    "previewPDF": "Xem trước PDF",
    "loadingFont": "Đang tải font tiếng Nhật...",
    "generatingPDF": "Đang tạo PDF...",
    "downloading": "Đang tải xuống...",
    "completed": "Hoàn tất",
    "step1Desc": "Vui lòng điền thông tin cá nhân của bạn. Nên viết tên bằng chữ Latinh và chữ Katakana chính xác.",
    "step2Desc": "Địa chỉ và thông tin liên hệ của bạn tại Nhật Bản. Nhập đúng mã bưu điện để các công ty dễ liên lạc.",
    "step3Desc": "Thêm lịch sử học tập (trường học, cao đẳng, đại học) theo định dạng năm và tháng.",
    "step4Desc": "Nhập kinh nghiệm làm việc, chức vụ và ngày tháng. Nên làm nổi bật kinh nghiệm lái xe.",
    "step5Desc": "Điền động lực, giới thiệu bản thân (Self-PR), sở thích và yêu cầu cá nhân.",
    "step6Desc": "Sơ sơ yếu lý lịch tiếng Nhật tiêu chuẩn đã được tạo. Bạn có thể xem trước hoặc tải xuống bên dưới.",
    "step6Title": "Hoàn tất! Đã tạo sơ yếu lý lịch PDF",
    "contactInfo": "Liên hệ & Địa chỉ",
    "remove": "Xóa bỏ",
    "schoolName": "Tên trường (ví dụ: Đại học ○○)",
    "degree": "Bằng cấp/Chuyên ngành (ví dụ: Cử nhân)",
    "company": "Công ty",
    "companyName": "Tên công ty",
    "position": "Vị trí (ví dụ: Tài xế xe tải)",
    "startDate": "Ngày bắt đầu",
    "endDate": "Ngày kết thúc",
    "currentPositionCheckbox": "Hiện đang làm việc tại đây",
    "addWork": "Thêm kinh nghiệm làm việc",
    "addEducation": "Thêm học vấn",
    "licensesQualifications": "Bằng cấp & Giấy phép",
    "otherCertificates": "Chứng chỉ đặc biệt",
    "finishBtn": "Hoàn tất",
    "callBtn": "Gọi điện",
    "fullNameLabel": "Họ và tên",
    "katakanaNameLabel": "Cách viết bằng Katakana",
    "fullNameHint": "Nhập bằng chữ Latinh (Ví dụ: ALIMOV ANVAR) hoặc chữ Kanji (Ví dụ: 山田 太郎) để đúng tiêu chuẩn Nhật.",
    "furiganaHint": "Phát âm tên bằng chữ Katakana Nhật Bản (Ví dụ: アリモフ アンバル hoặc ヤマダ タロウ).",
    "dobHint": "Chọn ngày sinh theo thứ tự: ngày, tháng và năm niên hiệu Nhật Bản.",
    "day": "Ngày",
    "month": "Tháng",
    "year": "Năm",
    "motivationPR": "Động lực & Giới thiệu bản thân",
    "refreshPreview": "Làm mới bản xem trước",
    "pdfPreviewRendering": "📄 Đang hiển thị bản xem trước...",
    "lic_futsu": "Bằng lái xe thường (Futsu)",
    "lic_chugata": "Bằng xe tải trung (Chugata)",
    "lic_oogata": "Bằng xe tải lớn (Oogata)",
    "lic_tokushu": "Bằng xe chuyên dụng (Tokushu)",
    "cert_forklift": "Xe nâng",
    "cert_crane": "Cần cẩu",
    "cert_towing": "Kéo xe",
    "admissionDateLabel": "Ngày nhập học",
    "gradDateLabel": "Ngày tốt nghiệp",
    "openInNewTab": "Mở trong tab mới"
  },
  "zh": {
    "createResume": "创建日文简历 (履歴書)",
    "downloadPDF": "下载 PDF",
    "postalCodeLabel": "邮政编码",
    "furiganaLabel": "振假名 (姓名读音)",
    "genderLabel": "性别",
    "male": "男",
    "female": "女",
    "phoneLabel": "电话号码",
    "motivationLabel": "申请动机",
    "selfPRLabel": "自我推荐 (Self-PR)",
    "hobbiesLabel": "兴趣与特长",
    "personalRequestsLabel": "个人希望栏",
    "resumeBuilderTitle": "日文简历生成器",
    "stepLabel": "步骤",
    "nextBtn": "下一步",
    "prevBtn": "上一步",
    "previewPDF": "预览 PDF",
    "loadingFont": "正在加载日文字体...",
    "generatingPDF": "正在生成 PDF...",
    "downloading": "正在下载...",
    "completed": "下载完成",
    "step1Desc": "请填写个人信息。建议准确填写英文及片假名姓名读音。",
    "step2Desc": "您在日本的住址和联系方式。填写正确的邮政编码能让企业更快联系到您。",
    "step3Desc": "添加您的教育背景（学校、大学等），以年和月为格式。",
    "step4Desc": "输入您的工作经历、职位和起止日期。强烈建议突出您的驾驶经验。",
    "step5Desc": "填写您的申请动机、自我推荐（Self-PR）、兴趣爱好以及个人期望。",
    "step6Desc": "已成功生成标准日文简历 PDF。您可以在下方进行预览或下载。",
    "step6Title": "完成！日文简历 PDF 已生成",
    "contactInfo": "联系方式与地址",
    "remove": "删除",
    "schoolName": "学校名称（如：○○大学）",
    "degree": "学位/专业（如：学士）",
    "company": "公司",
    "companyName": "公司名称",
    "position": "职位（如：卡车司机）",
    "startDate": "开始日期",
    "endDate": "结束日期",
    "currentPositionCheckbox": "目前在此工作",
    "addWork": "添加工作经历",
    "addEducation": "添加教育背景",
    "licensesQualifications": "执照与资格",
    "otherCertificates": "特殊证书",
    "finishBtn": "完成",
    "callBtn": "拨打电话",
    "fullNameLabel": "姓名（罗马字或汉字）",
    "katakanaNameLabel": "片假名读音",
    "fullNameHint": "请输入罗马字（例：ALIMOV ANVAR）或汉字（例：山田 太郎）以符合日本简历标准。",
    "furiganaHint": "请输入您的名字的日文片假名读音（例：アリモフ アンバル 或 ヤマダ タロウ）。",
    "dobHint": "请按日、月、和历（年）的顺序选择您的出生日期。",
    "day": "日",
    "month": "月",
    "year": "年",
    "motivationPR": "申请动机与自我推荐",
    "refreshPreview": "刷新预览",
    "pdfPreviewRendering": "📄 正在生成 PDF 预览...",
    "lic_futsu": "普通执照 (Futsu)",
    "lic_chugata": "中型卡车执照 (Chugata)",
    "lic_oogata": "大型卡车执照 (Oogata)",
    "lic_tokushu": "特殊车辆执照 (Tokushu)",
    "cert_forklift": "叉车",
    "cert_crane": "起重机",
    "cert_towing": "牵引",
    "admissionDateLabel": "入学时间",
    "gradDateLabel": "毕业时间",
    "openInNewTab": "在新标签页中打开"
  },
  "ne": {
    "createResume": "जापानी बायोडाटा (Rirekisho)",
    "downloadPDF": "PDF डाउनलोड गर्नुहोस्",
    "postalCodeLabel": "पोस्टल कोड",
    "furiganaLabel": "फुरिगाना (नाम उच्चारण)",
    "genderLabel": "लिङ्ग",
    "male": "पुरुष",
    "female": "महिला",
    "phoneLabel": "फोन नम्बर",
    "motivationLabel": "आवेदन गर्ने कारण / प्रेरणा",
    "selfPRLabel": "आत्म-प्रचार (Self-PR)",
    "hobbiesLabel": "रुचि र विशेष सीपहरू",
    "personalRequestsLabel": "व्यक्तिगत अनुरोधहरू",
    "resumeBuilderTitle": "जापानी बायोडाटा निर्माणकर्ता",
    "stepLabel": "चरण",
    "nextBtn": "अर्को",
    "prevBtn": "पछाडि",
    "previewPDF": "PDF पूर्वावलोकन",
    "loadingFont": "जापानी फन्ट लोड हुँदैछ...",
    "generatingPDF": "PDF सिर्जना हुँदैछ...",
    "downloading": "डाउनलोड हुँदैछ...",
    "completed": "सम्पन्न भयो",
    "step1Desc": "कृपया आफ्नो व्यक्तिगत विवरण भर्नुहोस्। नाम रोमन र काताकाना दुवैमा स्पष्ट लेख्न सल्लाह दिइन्छ।",
    "step2Desc": "जापानमा तपाईंको ठेगाना र सम्पर्क विवरण। कम्पनीहरूलाई सम्पर्क गर्न सजिलो होस् भन्नका लागि सही पोस्टल कोड प्रविष्ट गर्नुहोस्।",
    "step3Desc": "आफ्नो शैक्षिक इतिहास (विद्यालय, कलेज, विश्वविद्यालय) वर्ष र महिनाको ढाँचामा थप्नुहोस्।",
    "step4Desc": "आफ्नो कामको इतिहास, पद र मितिहरू प्रविष्ट गर्नुहोस्। विशेष गरी ड्राइभिङ अनुभवलाई जोड दिन सिफारिस गरिन्छ।",
    "step5Desc": "आफ्नो प्रेरणा, आत्म-प्रचार (Self-PR), रुचि र व्यक्तिगत आवश्यकताहरू भर्नुहोस्।",
    "step6Desc": "तपाईंको मानक जापानी Rirekisho PDF तयार भएको छ। तपाईं तल पूर्वावलोकन गर्न वा डाउनलोड गर्न सक्नुहुन्छ।",
    "step6Title": "तयार भयो! बायोडाटा PDF सिर्जना गरियो",
    "contactInfo": "सम्पर्क र ठेगाना",
    "remove": "हटाउनुहोस्",
    "schoolName": "विद्यालय/विश्वविद्यालयको नाम (उदा: ○५ विश्वविद्यालय)",
    "degree": "शैक्षिक उपाधि/तह (उदा: स्नातक)",
    "company": "कम्पनी",
    "companyName": "कम्पनीको नाम",
    "position": "पद (उदा: ट्रक चालक)",
    "startDate": "सुरुवात मिति",
    "endDate": "समाप्ति मिति",
    "currentPositionCheckbox": "हाल यहाँ कार्यरत छु",
    "addWork": "कामको इतिहास थप्नुहोस्",
    "addEducation": "शिक्षा थप्नुहोस्",
    "licensesQualifications": "लाइसेन्स र योग्यताहरू",
    "otherCertificates": "विशेष प्रमाणपत्रहरू",
    "motivationPR": "प्रेरणा र आत्म-प्रचार",
    "finishBtn": "समाप्त गर्नुहोस्",
    "callBtn": "फोन गर्नुहोस्",
    "fullNameLabel": "पूरा नाम",
    "katakanaNameLabel": "काताकाना उच्चारण",
    "fullNameHint": "जापानी मानकों के लिए अंग्रेजी अक्षरों (उदा. ALIMOV ANVAR) या कांजी (उदा. 山田 太郎) में दर्ज करें।",
    "furiganaHint": "जापानी काताकाना में अपने नाम का उच्चारण दर्ज करें (उदा. アリモフ アンバル या ヤマダ ताロウ)।",
    "dobHint": "अनुक्रम में अपनी जन्म तिथि चुनें: दिन, महीना और जापानी युग वर्ष।",
    "day": "दिन",
    "month": "महीना",
    "year": "वर्ष",
    "refreshPreview": "पूर्वावलोकन पुन: लोड गर्नुहोस्",
    "pdfPreviewRendering": "📄 PDF पूर्वावलोकन लोड हुँदैछ...",
    "lic_futsu": "साधारण सवारी साधन (Futsu)",
    "lic_chugata": "मध्यम ट्रक (Chugata)",
    "lic_oogata": "ठूलो ट्रक (Oogata)",
    "lic_tokushu": "विशेष सवारी साधन (Tokushu)",
    "cert_forklift": "फोर्कलिफ्ट",
    "cert_crane": "क्रेन",
    "cert_towing": "टोइङ",
    "admissionDateLabel": "भर्ना मिति",
    "gradDateLabel": "स्नातक मिति",
    "openInNewTab": "नयाँ ट्याबमा खोल्नुहोस्"
  }
}
